---
# tasks file for gamedayalpha
- hosts: bal
  become: true
  become_user: root
  vars_files:
    - ../vars/main.yml
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
  gather_facts: no
  tasks:
  - name: Include a file
    include: seeders/api.yml
    static: yes

# run seeder
